### ISSUE TITLE
Unable to open in vs 2010

### ISSUE THREAD

**Issue by miljbee** [jishi/Jishi.StreamToSonos#1]
I think that if you target it to .net 4 instead of 4.5, il will work.

For interrested users, It can be converted manually
see : http://stackoverflow.com/questions/15405108/visual-studio-2012-project-wont-open-in-2010

**Comment by jishi** [comment]
Well, I don't think it will be possible anyway, since the source utilizes some of the new async features from 4.5. I think it would open directly in the Express version of VS2012, the C# edition.

**Comment by miljbee** [comment]
OK thanks for your reply

JB ROBERT
https://google.com/+JeanBaptisteROBERT
